### ISSUE TITLE
[FCM] Add data to beers topic

### ISSUE THREAD

**Issue by mstrk** [Cloudoki/appdoki-be#5]
Add data to [this implementation](https://github.com/Cloudoki/appdoki-be/blob/main/app/users.go#L240)

The ideal data payload would be the same as `${API_URL}/beers` and `${API_URL}/users`:
```ts
// for beers topic
type Beer = {
  beers: number,
  giver: {
    id: string,
    name: string,
    email: string,
    picture: string,
  },
  receiver: {
    id: string,
    name: string,
    email: string,
    picture: string,
  },
  givenAt: string,
}

// for users(?) topic
type User = {
  id: string,
  name: string,
  email: string,
  picture: string,
}
```
this will allow the app to shift the data without doing a fresh request.

Also on the implementation options look for `contentAvailable` and `priority`, they should be `true` and `high` so we can handle messages in the background. See the example below:

```ts
// This is a js example, should have a similar API in go.
{
  data: {
    owner: JSON.stringify(owner),
    user: JSON.stringify(user),
    picture: JSON.stringify(picture),
  },
},
{
  // Required for background/quit data-only messages on iOS
  contentAvailable: true,
  // Required for background/quit data-only messages on Android
  priority: 'high',
}
```

**Comment by s1moe2** [comment]
@mstrk 
Added payload configuration options for Android/iOS.
Changed data field of FCM message to include payloads as in the API:
- beer transfer payload: https://github.com/Cloudoki/appdoki-be/blob/main/app/users.go#L244
- new user payload: https://github.com/Cloudoki/appdoki-be/blob/main/app/auth.go#L243

This last one changed from containing individual fields to have a `user` object instead.

Note:
Querying the API is always going to be more reliable and consistent because there is no guarantee that the messages will reach the devices entirely and in 100% correct order. In the event of a few messages arriving in the wrong order, the app may end up in an inconsistent state. This may not be harmful in some cases and generally ok in the app's context but good to keep in mind.

**Comment by mstrk** [comment]
Yup, thanks.

We receive an event in the app when messages don’t arrive to the device, I'll request fresh data on these occasions. I'll use the `givenAt` property to sort the data after the updates and we should be good.

For the users I'll just shift it on top of the data and call it a feature xD

cheers,
